server:
  port: 8443

spring:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mysql://localhost:3306/library_api?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: root
      password: 509680
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect